.PHONY: test run-1-test run-1-real run-2-test run-2-real

test:
	uv run pytest

run-1-test:
	uv run src/part_1.py --input-file test-input.txt
run-1-real:
	uv run src/part_1.py --input-file input.txt

run-2-test:
	uv run src/part_2.py --input-file test-input-2.txt
run-2-real:
	uv run src/part_2.py --input-file input.txt
